#!/bin/sh
set -e  # Exit immediately if any command exits with a non-zero status

echo ""
echo '* Verify dependencies'
go mod verify

echo ""
echo '* Run: go-modernize'
modernize -test ./...

echo ""
echo '* Run: golangci'
golangci-lint run ./...

echo ""
echo '* Run: all tests and generate coverage report'
go test $(go list ./... | grep -Ev 'internal/testutils') -covermode=atomic